name: deploy 

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    - name: Install Surge
      run: npm install --global surge
    
    - name: Run Surge
      run: surge ./ venomaz.surge.sh --token ${{secrets.MHDSECRET}} 
