name: Deployment to Surge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@vs

      - name: installing node
      - uses: actions/setup-node@v3
        with:
           node-version: '16'

      - name: installing surge
      - run: npm install --global surge

      - name: delploy Web Application
      - run: surge ./ MedisterJaxx_JS.surge.sh --token ${{ secrets.PSEUDOSECRET }}
